app/urls.py
from flask import Blueprint

from app.views import (
    text_to_audio_view, grapheme_log_view,
    upload_file_view
)

interface = Blueprint('interface', __name__)

interface.add_url_rule(
    '/', view_func=text_to_audio_view,
    methods=['GET', 'POST']
)
interface.add_url_rule(
    '/grapheme-log/<int:grapheme_id>',
    view_func=grapheme_log_view,
    methods=['GET']
)

interface.add_url_rule(
    '/upload-file', view_func=upload_file_view,
    methods=['POST', 'GET']
)

app/views.py
import json
import os
import tempfile
import time

from flask import render_template, request, redirect, url_for
from sqlalchemy.exc import SQLAlchemyError

from app.ipa_phonemizer import (
    phonemize, get_grapheme2phonemes_from_model,
    enrich_model_phonemes_with_db, phonemes_to_string,
    tokenize, is_word
)
from app.matcha_utils import synthesize_matcha_audios
from app.utils import get_word2phones_from_textgrid

AUDIO = 'static/audio/utterance.wav'
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 Mb


def text_to_audio_view():
    # import here, otherwise circular import
    from app import db
    from app.db_utils import (
        add_graphemes_and_log, fetch_grapheme2phoneme,
        fetch_grapheme_ids_by_name
    )

    if request.method == 'POST':
        form = request.form
        text = form['text']
        words = tokenize(text)

        if form.get('generate'):
            word2db_phoneme = fetch_grapheme2phoneme(words)
            word2grapheme_id = fetch_grapheme_ids_by_name(
                word2db_phoneme.keys())
            word2model_phonemes = get_grapheme2phonemes_from_model(words)
            word2phonemes, word2picked_phoneme, phonemized_str = (
                phonemize(words, word2model_phonemes, word2db_phoneme)
            )
            
        elif form.get('regenerate') or form.get('confirm'):
            # TODO: it would be nice to show to a user "saved"
            # TODO: handle situation with the wrong input from the user
            word2model_phonemes = json.loads(form['jsoned_word2model_phonemes'])
            word2phonemes = json.loads(form["jsoned_word2phonemes"])
            word2phonemes, word2picked_phoneme = pick_phoneme_from_form(
                word2phonemes, form)
            phonemized_str = phonemes_to_string(words, word2picked_phoneme)

            if form.get('confirm'):
                try:
                    add_graphemes_and_log(word2picked_phoneme)
                    db.session.commit()
                except SQLAlchemyError as e:
                    # TODO: show the error to the user
                    db.session.rollback()
                    print("Error!", e)
                    return redirect(url_for('interface.text_to_audio_view'))
            
            # fetch db phonemes after saving them to db
            word2db_phoneme = fetch_grapheme2phoneme(words)
            word2grapheme_id = fetch_grapheme_ids_by_name(word2db_phoneme.keys())

        else:
            raise NotImplementedError

        phoneme2audio = synthesize_matcha_audios(text, phonemized_str, word2phonemes)
        audio = timestamp_audio(AUDIO)

        return render_template(
            'text-to-audio.html', audio=audio,
            phoneme2audio=phoneme2audio,
            text=text, word2phonemes=word2phonemes,
            word2picked_phoneme=word2picked_phoneme,
            jsoned_word2phonemes=json.dumps(word2phonemes, ensure_ascii=False),
            word2db_phoneme=word2db_phoneme,
            word2model_phonemes=word2model_phonemes,
            jsoned_word2model_phonemes = json.dumps(
                word2model_phonemes, ensure_ascii=False),
            word2grapheme_id=word2grapheme_id,
            is_word=is_word
        )

    return render_template('text-to-audio.html')


def grapheme_log_view(grapheme_id):
    from app.db_utils import fetch_grapheme_logs, fetch_grapheme
    from app.models import Grapheme

    grapheme_logs = fetch_grapheme_logs(grapheme_id)
    grapheme, phoneme = fetch_grapheme(grapheme_id)

    return render_template(
        'grapheme-log.html', 
        grapheme=grapheme,
        phoneme=phoneme,
        grapheme_logs=grapheme_logs)


def upload_file_view():
    # imported here due to circular import
    from app import db
    from app.db_utils import filter_out_existing_words, save_word2phones

    save_flag = False
    errors = []
    new_words2phones = {}
    file_name = None
    discarded_words = []
    
    file = request.files.get('file')
    
    if file:
        file_name = file.filename[:50]
        file_content = file.read()
        if len(file_content) > MAX_FILE_SIZE:
            errors.append('Please upload a file which is less than 5 Mb')
        else: 
            file.seek(0)

            # Create a temporary file with a secure filename in order for textgrid to read it
            # (textgrid can't read from a file object, it needs a path in a str format)
            _, temp_path = tempfile.mkstemp(suffix=os.path.splitext(file.filename)[1])
            
            try:
                with open(temp_path, 'wb') as temp_file:
                    temp_file.write(file_content)
                word2phones = get_word2phones_from_textgrid(temp_path)
                if not word2phones:
                    errors.append('No words found in the TextGrid. Please upload a new TextGrid.')
                new_words2phones = filter_out_existing_words(word2phones)
                if not new_words2phones:
                    errors.append('All words from the TextGrid are already in the database.')

            except Exception as e:
                errors.append(f'An error happened during uploading of your file: {e}')

            finally:
                os.remove(temp_path)

    elif request.form.get('confirm_changes'):
        form = request.form

        file_name  = form['file_name']
        new_words2phones = {}
        discarded_words = []
        for word in json.loads(form['jsoned_new_words2phones']):
            phones_from_form = form.getlist(word)
            picked_phones = [phone for phone in phones_from_form if phone]
            if not picked_phones or picked_phones[0] == 'discard':
                picked_phone = None
                discarded_words.append(word)
            else:
                picked_phone = picked_phones[0]
            new_words2phones[word] = picked_phone
        try:                
            save_word2phones(new_words2phones)
            db.session.commit()
            save_flag = True
        except SQLAlchemyError as e:
            print(f'Error: {e}')
            errors.append('An error happened during saving of your file')
            db.session.rollback()
            
        # in order to display it in the same format in html (word: [phones]),
        # wrap each phone in a list
        new_words2phones = {
            word: [phone] 
            if phone is not None 
            else [] 
            for word, phone in new_words2phones.items()
        }

    return render_template('upload-file.html', 
        new_words2phones=new_words2phones,
        file_name=file_name,
        jsoned_new_words2phones=json.dumps(new_words2phones, ensure_ascii=False),
        save_flag=save_flag,
        errors=errors,
        discarded_words=discarded_words,
    )


def timestamp_audio(filename):
    # timestamp is needed since the audio is stored in the same path,
    # so the browser caches the audio and doesn't update it (== plays the old audio)
    timestamp = str(int(time.time()))
    return f'{filename}?v{timestamp}'


def pick_phoneme_from_form(word2phonemes, form):
    from app.db_utils import fetch_grapheme2phoneme

    word2picked_phoneme = {}
    for word, all_phonemes in word2phonemes.items() :
        if not is_word(word):
            continue
        # form phonemes: radio input -- either picked or orthographic
        form_phonemes = form.getlist(word)
        picked, manual_input = form_phonemes
        # manual for now is orthographic only!
        # there is no any validation here!
        if not manual_input:          
            word2picked_phoneme[word] = picked
        else:
            # if the phoneme is orthographic:
                # 1. get the phonemes from the model
                # 2. enrich the model phonemes with db phonemes
                # 3. pick the phoneme
                # 4. extend the word2phonemes with the new phonemes
            ipa_input = f'ipa_{word}'
            if form.get(ipa_input):
                word2picked_phoneme[word] = manual_input
                word2phonemes[word].append(manual_input)
            else:
                orthograpic = manual_input
                orthograpic2model_phonemes = get_grapheme2phonemes_from_model(
                    [orthograpic])
                orthograpic2db_phoneme = fetch_grapheme2phoneme([orthograpic])
                orthograpic2phonemes, orthograpic2picked_phoneme = (
                    enrich_model_phonemes_with_db(
                        orthograpic2model_phonemes,
                        orthograpic2db_phoneme))
                new_phonemes = [
                    phoneme 
                    for phoneme in orthograpic2phonemes[orthograpic] 
                    if phoneme not in all_phonemes
                ]
                picked_phoneme = orthograpic2picked_phoneme[orthograpic]
                word2picked_phoneme[word] = picked_phoneme
                word2phonemes[word].extend(new_phonemes)
    
    return word2phonemes, word2picked_phoneme

app/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Default Title{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='icons/ear.svg') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <style>
        .hidden { display: none; }
    </style>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

app/templates/text-to-audio.html
{% extends "base.html" %}

{% from "utils.html" import display_phoneme_input, upload_file_button %}

{% block title %}G2P Correction{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">

<!-- Loading Overlay -->
<div id="loadingOverlay" class="loading-overlay" style="display: none;">
    <div class="spinner"></div>
</div>

<!-- IPA Character Popup -->
<div id="ipaPopup" class="ipa-popup" style="display: none;"></div>

<div class="container-fluid">
  <div class="row justify-content-center align-items-center min-vh-100">
    <div class="col-md-8">
      {{ upload_file_button() }}
      {% if audio %}
        <audio id="audioPlayer" style="display:none;">
          <source src="{{ audio }}" type="audio/wav">
          Your browser does not support the audio element.
        </audio>
        <script>
          document.addEventListener('DOMContentLoaded', function() {
            var audioPlayer = document.getElementById('audioPlayer');
              document.getElementById('loadingOverlay').style.display = 'flex';
                if (audioPlayer) {
                  audioPlayer.play().then(function() {
                    document.getElementById('loadingOverlay').style.display = 'none';
                  })
                  .catch(function(error) {
                    console.error("Audio play failed:", error);
                    // Hide loading overlay on error
                    document.getElementById('loadingOverlay').style.display = 'none';
                  });
                }
              if (audioPlayer) {
                audioPlayer.onended = function() {
                  document.getElementById('listenAgainBtn').style.display = 'inline-block';
                };
              }
          });
          </script>
      {% endif %}
      <div class="card p-4 mb-4">
        <h3 class="text-center mb-4">G2P Correction</h3>
        <form action="{{ url_for('interface.text_to_audio_view') }}" method="POST">
          <div class="input-group mb-3">
            <input type="text" class="form-control" id="inputText" name="text" placeholder="Enter sentence (100 characters maximum)" maxlength="100" {% if text %} value="{{ text }}" {% endif %}>
            <a class="btn btn-secondary" href="{{ url_for('interface.text_to_audio_view') }}">Clear</a>
            <button type="submit" class="btn btn-primary" value="Generate" name="generate">Generate</button>
            <button type="button" class="btn btn-info ml-2" id="listenAgainBtn" style="display: none;" onclick="listenAgain()">
                <img src="../static/icons/ear.svg" alt="Listen Again" style="width: 16px; height: 16px;">
            </button>
          </div>
        {% if word2phonemes %}
          <input type="hidden" name="jsoned_word2phonemes" value='{{ jsoned_word2phonemes }}'>
          <input type="hidden" name="jsoned_word2model_phonemes" value='{{ jsoned_word2model_phonemes }}'>
          <div class="mt-4">
            {% for word, phonemes in word2phonemes.items() %}
              {% if is_word(word) %}
                {% set db_phoneme = word2db_phoneme[word] %}
                {% set phonemes_from_model = word2model_phonemes[word] %}
                {% set checked_phoneme = word2picked_phoneme[word] %}
                <div class="card mb-3">
                  <div class="card-header" onclick="toggleVariations('{{ word }}')">
                    <button type="button" class="btn btn-link" onkeypress="toggleVariations('{{ word }}')" 
                            onclick="toggleVariations('{{ word }}')"  data-word="{{ word }}">
                      <img onkeypress="toggleVariations('{{ word }}')" onclick="toggleVariations('{{ word }}')" 
                            src="../static/icons/arrow-bar-down.svg" alt="Toggle Variations">
                    </button>
                    {{ word }}
                    {% if word in word2db_phoneme %}
                      {% set grapheme_id = word2grapheme_id[word] %}
                      <a href="{{ url_for('interface.grapheme_log_view', grapheme_id=grapheme_id) }}"><img src="../static/icons/arrow-up-right-square.svg" alt="Grapheme Log"></a> 
                    {% endif %}
                  </div>
                  <div class="card-body" id="{{ word }}_variations" style="display: none;">
                    <div class="form-check">
                      {% if db_phoneme %}
                        {{ display_phoneme_input(
                          word, db_phoneme,
                          audio_name=phoneme2audio[db_phoneme],
                          index=0, 
                          checked=True,
                          db_phoneme=True,
                          )
                        }}
                      {% endif %}
                      {% for phoneme in phonemes if phoneme != db_phoneme %}
                        {{ display_phoneme_input(
                          word, phoneme,
                          audio_name=phoneme2audio[phoneme],
                          index=loop.index, 
                          checked=phoneme==checked_phoneme,
                          db_phoneme=False,
                          from_form=phoneme not in phonemes_from_model) 
                        }}
                      {% endfor %}
                      <div class="form-check">
                        <input type="radio" class="form-check-input" name="{{ word }}" value="{{ phoneme }}" id="{{ loop.index }}">
                        <input name="{{ word }}" placeholder="Provide your own" id="input_{{ loop.index }}" autocomplete="off" 
                        onkeyup="handleTyping(event, '{{ loop.index }}')">                        
                        <input type="checkbox" id="checkbox_{{loop.index}}" name="ipa_{{ word }}"> 
                        <label for="checkbox_{{loop.index}}">IPA?</label> 
                      </div>
                    </div>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="button-container">
            <button type="submit" class="btn btn-primary mr-10" value="Regenerate" 
                    name="regenerate">Test</button>
            <button type="submit" class="btn btn-success" value="Confirm" 
                    name="confirm">Confirm</button>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<audio id="audioPlayer" controls style="display:none;">
  Your browser does not support the audio element.
</audio>

<script>
  // IPA Characters Mapping
  const ipaMapping = {
    'a': ['ɑ', 'æ', 'ɐ', 'ʌ'],
    'd': ['ð'],
    'e': ['ə', 'ɚ', 'ɛ', 'ɜ'],
    'i': ['ɪ', 'ᵻ'],
    'n': ['ŋ'],
    'o': ['ɔ', 'œ', 'ɒ',],
    'r': ['ɾ', 'ɹ'],
    's': ['ʃ'],
    't': ['θ'],
    'u': ['ʊ'],
    'z': ['ʒ'],
    ',': ['ˌ'],
    ':': ['ː']
  };

  function playAudio(audioSrc) {
    var audioPlayer = document.getElementById('audioPlayerPhoneme');
    audioPlayer.src = audioSrc;
    audioPlayer.play();
  }


  function toggleVariations(word) {
    var variationsDiv = document.getElementById(word + "_variations");
    var arrowImg = document.querySelector('[data-word="' + word + '"] img');
    if (variationsDiv.style.display === "none") {
        variationsDiv.style.display = "block";
        document.querySelector('button[data-word="' + word + '"] i');
        arrowImg.src = "../static/icons/arrow-bar-up.svg";
    } else {
        variationsDiv.style.display = "none";
        document.querySelector('button[data-word="' + word + '"] i');
        arrowImg.src = "../static/icons/arrow-bar-down.svg";
    }
  }

  function listenAgain() {
        var audioPlayer = document.getElementById('audioPlayer');
        if (audioPlayer) {
            audioPlayer.currentTime = 0;
            audioPlayer.play()
            .catch(error => console.error("Audio play failed:", error));
        }
    }
    
    function selectRadio(index) {
        document.getElementById(index).checked = true;
    }

    var ipaPopupOpen = false;

    function showIPAPopup(event, index) {
        ipaPopupOpen = true;
        var inputChar = event.target.value.slice(-1);   // get the last input character
        var ipaOptions = ipaMapping[inputChar];         // get the mapping options
        if (ipaOptions && ipaOptions.length > 0) {
            var popup = document.getElementById('ipaPopup');
            popup.innerHTML = ''; 
            // generate option buttons based on the character
            ipaOptions.forEach(function(ipaChar) {
                var button = document.createElement('button');
                button.textContent = ipaChar;
                button.onclick = function() {
                    insertIPA(ipaChar, index);
                };
                popup.appendChild(button);
            });
            // set position for popup
            var inputField = document.getElementById("input_" + index);
            var caretPosition = getCaretPosition(inputField);
            var inputRect = event.target.getBoundingClientRect();
            // Calculate the position of the popup
            var topOffset = inputRect.top + window.pageYOffset + 30; // Adjust as needed
            var leftOffset = inputRect.left + window.pageXOffset + caretPosition.left;

            // Set the position of the popup
            popup.style.top = topOffset + 'px';
            popup.style.left = leftOffset + 'px';
            popup.style.display = 'block';
            if (ipaPopupOpen) {
                // Add event listener for TAB key press
                document.addEventListener('keydown', tabKeyHandler)
            }
        } else {
            hideIPAPopup();
        }
    }
    
    function tabKeyHandler(event) {
        if (event.key === 'Tab') {
            // If IPA popup is visible, focus on the first button in the popup
            if (document.getElementById('ipaPopup').style.display === 'block') {
                event.preventDefault(); // Prevent default TAB behavior
                // Get all buttons in the IPA popup
                var buttons = document.querySelectorAll('#ipaPopup button');
                var focusedButton = document.activeElement;
                var index = Array.from(buttons).indexOf(focusedButton);
                // If no button is focused or the focused button is the last one, focus on the first button
                if (index === -1 || index === buttons.length - 1) {
                    buttons[0].focus();
                } else { // Focus on the next button
                    buttons[index + 1].focus();
                }
            }
        }
    }
    // Function to get the caret position in the input field
    function getCaretPosition(inputField) {
        var selection = window.getSelection();
        var range = selection.getRangeAt(0);
        var rect = range.getBoundingClientRect();
        return {
            top: rect.top,
            left: rect.left
        };
    }
    // insert selected character into input field
    function insertIPA(ipaChar, index) {
        var inputField = document.getElementById("input_" + index);
        inputField.value = inputField.value.slice(0, -1) + ipaChar; 
        inputField.focus();
        hideIPAPopup(); 
    }

    function hideIPAPopup() {
        document.getElementById('ipaPopup').style.display = 'none';
        ipaPopupOpen = false;
    }

    function handleTyping(event, index) {
        // Show the IPA popup (you can replace this with your existing IPA logic)
        showIPAPopup(event, index);
        
        // Check the corresponding radio button
        document.getElementById(index).checked = true;
    }
</script>

{% endblock %}

app/templates/upload-file.html
{% extends "base.html" %}

{% from "utils.html" import display_phone_from_textgrid, upload_file_button %}

{% block title %}Upload TextGrid{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../static/css/styles.css">

<!-- Loading Overlay -->
<div id="loadingOverlay" class="loading-overlay" style="display: none;">
    <div class="spinner"></div>
</div>

<!-- IPA Character Popup -->
<div id="ipaPopup" class="ipa-popup" style="display: none;"></div>

<div class="container-fluid">
  <div class="row justify-content-center align-items-center min-vh-100">
    <div class="col-md-8">
      {{ upload_file_button(back=True) }}
      <div class="card p-4 mb-4">
        <h3 class="text-center mb-4">G2P Correction: Uploading a new TextGrid</h3>
        <p class="text-center" style="font-family: 'Courier New', Courier, monospace; font-size: 1em; color: #380aee;">
          {% if file_name %}
            Filename: {{ file_name }}
          {% endif %}
          
        </p>
      </div>

      <div class="mt-4">
        {% if not file_name %}
          <div class="alert alert-warning" role="alert">
            No file found. Please upload a new TextGrid.
          </div>
        {% elif errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% elif save_flag %}
          <div class="alert alert-success" role="alert">
            The words and transcriptions have been saved successfully.
          </div>
        {% else %}
          <div class="alert alert-info" role="alert">
            Please correct the phonetic transcriptions for the following words.
          </div>
        {% endif %}
        {% if new_words2phones %}
          <form action="{{ url_for('interface.upload_file_view') }}" method="POST">
            <input type="hidden" name="jsoned_new_words2phones" value='{{ jsoned_new_words2phones }}'>
            <input type="hidden" name="saved_flag" value="{{ saved_flag }}">
            <input type="hidden" name="file_name" value="{{ file_name }}">
            {% for word, phones in new_words2phones.items() %}
              <div class="card mb-3">
                <div class="card-header" onclick="toggleVariations('{{ word }}')">
                  <button type="button" class="btn btn-link" onkeypress="toggleVariations('{{ word }}')" 
                          onclick="toggleVariations('{{ word }}')" data-word="{{ word }}">
                    <img src="../static/icons/arrow-bar-down.svg" alt="Toggle Variations">
                  </button>
                  {{ word }}
                </div>
                <div class="card-body" id="{{ word }}_variations" 
                      {% if save_flag %} style="display: none;"
                      {% else %} style="display: block;" {% endif %}
                >
                  {% if word in discarded_words %}
                    <p style="color: #ee0a0a;">This word was discarded.</p>
                  {% else %}
                    {% for phone in phones %}
                      {{ display_phone_from_textgrid(word, phone, index=loop.index, checked=loop.index == 1) }}
                    {% endfor %}
                  {% endif %}
                  <div class="form-check mt-3">
                    <input type="radio" class="form-check-input" name="{{ word }}" value="{{ phoneme }}" id="{{ loop.index }}">
                    <input name="{{ word }}" placeholder="Provide your own" id="input_{{ loop.index }}" autocomplete="off" 
                           onkeyup="handleTyping(event, '{{ loop.index }}')">    
                  </div>
                  {% if word not in discarded_words %}
                    <div class="form-check mt-3">
                      <input type="radio" class="form-check-input" name="{{ word }}" value="discard" id="delete_{{ word }}">
                      <label class="form-check-label text-danger" for="delete_{{ word }}">Discard this word</label>
                    </div>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="button-container">
              <button type="submit" class="btn btn-success" value="Confirm" 
                      name="confirm_changes">Confirm</button>
            </div>
          </form>
        {% endif %}
      </div>
    </div> 
  </div>
</div>

<script>
  // Function to check radio button when the custom input is filled
  function checkCustom(word) {
    document.getElementById(word).checked = true;
  }
  // IPA Characters Mapping
  const ipaMapping = {
    'a': ['ɑ', 'æ', 'ɐ', 'ʌ'],
    'd': ['ð'],
    'e': ['ə', 'ɚ', 'ɛ', 'ɜ'],
    'i': ['ɪ', 'ᵻ'],
    'n': ['ŋ'],
    'o': ['ɔ', 'œ', 'ɒ',],
    'r': ['ɾ', 'ɹ'],
    's': ['ʃ'],
    't': ['θ'],
    'u': ['ʊ'],
    'z': ['ʒ'],
    ',': ['ˌ'],
    ':': ['ː']
  };


  function toggleVariations(word) {
    var variationsDiv = document.getElementById(word + "_variations");
    var arrowImg = document.querySelector('[data-word="' + word + '"] img');
    if (variationsDiv.style.display === "none") {
        variationsDiv.style.display = "block";
        document.querySelector('button[data-word="' + word + '"] i');
        arrowImg.src = "../static/icons/arrow-bar-up.svg";
    } else {
        variationsDiv.style.display = "none";
        document.querySelector('button[data-word="' + word + '"] i');
        arrowImg.src = "../static/icons/arrow-bar-down.svg";
    }
  }
    
    function selectRadio(index) {
        document.getElementById(index).checked = true;
    }

    var ipaPopupOpen = false;

    function showIPAPopup(event, index) {
        ipaPopupOpen = true;
        var inputChar = event.target.value.slice(-1);   // get the last input character
        var ipaOptions = ipaMapping[inputChar];         // get the mapping options
        if (ipaOptions && ipaOptions.length > 0) {
            var popup = document.getElementById('ipaPopup');
            popup.innerHTML = ''; 
            // generate option buttons based on the character
            ipaOptions.forEach(function(ipaChar) {
                var button = document.createElement('button');
                button.textContent = ipaChar;
                button.onclick = function() {
                    insertIPA(ipaChar, index);
                };
                popup.appendChild(button);
            });
            // set position for popup
            var inputField = document.getElementById("input_" + index);
            var caretPosition = getCaretPosition(inputField);
            var inputRect = event.target.getBoundingClientRect();
            // Calculate the position of the popup
            var topOffset = inputRect.top + window.pageYOffset + 30; // Adjust as needed
            var leftOffset = inputRect.left + window.pageXOffset + caretPosition.left;

            // Set the position of the popup
            popup.style.top = topOffset + 'px';
            popup.style.left = leftOffset + 'px';
            popup.style.display = 'block';
            if (ipaPopupOpen) {
                // Add event listener for TAB key press
                document.addEventListener('keydown', tabKeyHandler)
            }
        } else {
            hideIPAPopup();
        }
    }
    
    function tabKeyHandler(event) {
        if (event.key === 'Tab') {
            // If IPA popup is visible, focus on the first button in the popup
            if (document.getElementById('ipaPopup').style.display === 'block') {
                event.preventDefault(); // Prevent default TAB behavior
                // Get all buttons in the IPA popup
                var buttons = document.querySelectorAll('#ipaPopup button');
                var focusedButton = document.activeElement;
                var index = Array.from(buttons).indexOf(focusedButton);
                // If no button is focused or the focused button is the last one, focus on the first button
                if (index === -1 || index === buttons.length - 1) {
                    buttons[0].focus();
                } else { // Focus on the next button
                    buttons[index + 1].focus();
                }
            }
        }
    }
    // Function to get the caret position in the input field
    function getCaretPosition(inputField) {
        var selection = window.getSelection();
        var range = selection.getRangeAt(0);
        var rect = range.getBoundingClientRect();
        return {
            top: rect.top,
            left: rect.left
        };
    }
    // insert selected character into input field
    function insertIPA(ipaChar, index) {
        var inputField = document.getElementById("input_" + index);
        inputField.value = inputField.value.slice(0, -1) + ipaChar; 
        inputField.focus();
        hideIPAPopup(); 
    }

    function hideIPAPopup() {
        document.getElementById('ipaPopup').style.display = 'none';
        ipaPopupOpen = false;
    }

    function handleTyping(event, index) {
        // Show the IPA popup (you can replace this with your existing IPA logic)
        showIPAPopup(event, index);
        
        // Check the corresponding radio button
        document.getElementById(index).checked = true;
    }
</script>


{% endblock %}